### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by saiphaneendra-drycoder** [Neerajj9/Text-Detection-using-Yolo-Algorithm-in-keras-tensorflow#4]
where is text_detect.h5 file in model directory?

**Comment by Neerajj9** [comment]
It's on drive. The link is given in the readme file.

**Comment by saiphaneendra-drycoder** [comment]
Couldnt find
Can you can text_detect.h5 file

**Comment by saiphaneendra-drycoder** [comment]
Can you send text_detect.h5 file to me.
